# Generated by Django 3.1 on 2020-11-03 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traveller_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Operators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operators_name', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('class_type', models.CharField(max_length=250)),
                ('depature_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('nationality', models.CharField(max_length=250)),
                ('selled_seats', models.CharField(blank=True, max_length=500)),
                ('available_seat', models.IntegerField()),
                ('browse_route', models.CharField(max_length=250)),
                ('day_night', models.CharField(max_length=250)),
                ('images', models.TextField()),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Sale_Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traveller_name', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('phone_no', models.CharField(max_length=250)),
                ('note', models.CharField(max_length=500)),
                ('busId', models.CharField(max_length=250)),
                ('busname', models.CharField(max_length=250)),
                ('route', models.CharField(max_length=250)),
                ('depaturetime', models.CharField(max_length=500)),
                ('arrivaltime', models.CharField(max_length=500)),
                ('seatnumbers', models.CharField(max_length=500)),
                ('subtotal', models.CharField(max_length=500)),
                ('buyingdate', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=250)),
                ('destination', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('operators', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Routes_id', to='Applications.operators')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
